export const CITIES_BY_STATE: Record<string, string[]> = {
  "Andhra Pradesh": [
    "Achampet","Adilabad","Adoni","Amalapuram","Anakapalle","Anantapur","Araku Valley","Atmakur","Badvel","Bapatla",
    "Bhimavaram","Bobbili","Chirala","Chittoor","Dharmavaram","Dhone","Dowlaiswaram","Eluru","Gajapatinagaram","Giddalur",
    "Gonegandla","Gudivada","Gudur","Guntakal","Guntur","Hindupur","Jaganmohanreddy Nagar","Jammalamadugu","Kadapa",
    "Kakinada","Kalyandurg","Kandukur","Kanigiri","Kavali","Kodad","Kovvur","Kurnool","Macherla","Machilipatnam",
    "Madanapalle","Mandapeta","Markapur","Narasapur","Narasaraopet","Narsapuram","Nasvadu","Nellore","Nidadavole",
    "Nuzividu","Ongole","Palacole","Palakonda","Palmaner","Paravada","Parvathipuram","Pedana","Peddapuram","Pithapuram",
    "Proddatur","Pulivendula","Punganur","Rajahmundry","Rajam","Rajampet","Ramachandrapuram","Rampachodavaram",
    "Rayachoti","Rayadurg","Repalle","Salur","Samalkot","Srikakulam","Srikalahasti","Srisailam","Sullurpeta","Tadepalligudem",
    "Tadipatri","Tanuku","Tenali","Tirupati","Tiruvuru","Tuni","Uravakonda","Venkatagiri","Vijayawada","Vinukonda",
    "Visakhapatnam","Vizianagaram","Yemmiganur","Yerraguntla",
  ],
  "Arunachal Pradesh": [
    "Aalo","Along","Anini","Basar","Bomdila","Changlang","Daporijo","Deomali","Dirang","Hayuliang","Itanagar",
    "Jairampur","Khonsa","Koloriang","Likabali","Longding","Mechuka","Naharlagun","Namsai","Nirjuli","Pasighat",
    "Roing","Sagalee","Seppa","Tawang","Tezu","Yazali","Yupia","Ziro",
  ],
  "Assam": [
    "Abhayapuri","Barpeta","Barpeta Road","Biswanath Chariali","Bokajan","Bongaigaon","Charaideo","Chirang","Dergaon",
    "Dhemaji","Dhubri","Dibrugarh","Digboi","Diphu","Dispur","Doboka","Duliajan","Goalpara","Golaghat","Guwahati",
    "Haflong","Hailakandi","Hojai","Jorhat","Karimganj","Karbi Anglong","Kokrajhar","Lakhimpur","Lakhipur","Lanka",
    "Lumding","Maibong","Majuli","Mangaldoi","Margherita","Marigaon","Morigaon","Nagaon","Nalbari","North Lakhimpur",
    "Numaligarh","Rangia","Sadiya","Sibsagar","Silchar","Sivasagar","Sonari","Sonitpur","Tezpur","Tinsukia",
    "Titabar","Udalguri",
  ],
  "Bihar": [
    "Amarpur","Araria","Arrah","Arwal","Aurangabad","Bagaha","Banka","Barhiya","Barh","Baurnia","Begusarai",
    "Benipur","Bettiah","Bhabua","Bhagalpur","Birpur","Bodh Gaya","Buxar","Chhapra","Darbhanga","Dehri","Dumraon",
    "Forbesganj","Gaya","Gopalganj","Hajipur","Hilsa","Jahanabad","Jamui","Jamalpur","Jehanabad","Katihar","Khagaria",
    "Kishanganj","Lakhisarai","Lalganj","Madhepura","Madhubani","Maharajganj","Maner","Motihari","Motipur","Munger",
    "Muzaffarpur","Nalanda","Naugachia","Nawada","Patna","Phulwari Sharif","Purnia","Rajgir","Raxaul","Rohtas",
    "Saharsa","Samastipur","Sasaram","Seikhpura","Sheikhpura","Sheohar","Sitamarhi","Siwan","Supaul","Vaishali",
  ],
  "Chhattisgarh": [
    "Ambikapur","Balod","Baloda Bazar","Balrampur","Bemetara","Bhilai","Bhatapara","Bilaspur","Bijapur","Champa",
    "Chirmiri","Dantewada","Dhamtari","Dongargarh","Durg","Gariaband","Jagdalpur","Janjgir","Jashpur","Kanker",
    "Kawardha","Kondagaon","Korba","Koriya","Kota","Kumhari","Kurud","Mahasamund","Mungeli","Narayanpur",
    "Pathalgaon","Raigarh","Raipur","Rajnandgaon","Sakti","Sarangarh","Surajpur","Surguja",
  ],
  "Goa": [
    "Aldona","Bicholim","Calangute","Canacona","Candolim","Cuncolim","Curchorem","Curti","Dabolim","Dharbandora",
    "Fatorda","Mapusa","Margao","Mormugao","Panjim","Panaji","Pernem","Ponda","Porvorim","Quepem","Sanguem",
    "Sanquelim","Sanvordem","Tiswadi","Valpoi","Vasco da Gama",
  ],
  "Gujarat": [
    "Ahmedabad","Ahwa","Amreli","Anand","Anjar","Anklav","Bharuch","Bhavnagar","Bhuj","Botad","Chhota Udaipur",
    "Dahod","Dang","Deesa","Devbhumi Dwarka","Dhandhuka","Dhansura","Dhoraji","Gandhinagar","Gir Somnath","Godhra",
    "Himmatnagar","Idar","Jamnagar","Jetpur","Junagadh","Kadi","Kalol","Kapadwanj","Kathlal","Khambhat","Kheda",
    "Kutch","Lathi","Lunavada","Mahesana","Mahisagar","Malpur","Manavadar","Mandvi","Mahuva","Mehmedabad","Modasa",
    "Morbi","Nadiad","Navsari","Okha","Padra","Palanpur","Pali","Palitana","Patan","Petlad","Porbandar",
    "Rajkot","Rajpipla","Ranavav","Sabarkantha","Sanand","Savarkundla","Sidhpur","Surat","Surendranagar","Talaja",
    "Tapi","Umreth","Una","Vallabh Vidyanagar","Valsad","Veraval","Viramgam","Visavadar","Vyara","Wadhwan",
  ],
  "Haryana": [
    "Ambala","Ambala Cantonment","Assandh","Bahadurgarh","Bawal","Bhiwani","Charkhi Dadri","Ellenabad","Faridabad",
    "Fatehabad","Ferozepur Jhirka","Gohana","Gurgaon","Gurugram","Hansi","Hathin","Hisar","Hodal","Jagadhri",
    "Jhajjar","Jind","Kaithal","Kalka","Karnal","Kharkhoda","Kosli","Kurukshetra","Loharu","Mahendragarh",
    "Mewat","Morni Hills","Narnail","Narnaul","Narwana","Nuh","Panchkula","Panipat","Pataudi","Pehowa",
    "Pinjore","Ratia","Rewari","Rohtak","Safidon","Sirsa","Sohna","Sonipat","Taoru","Thanesar","Tohana",
    "Tosham","Yamunanagar",
  ],
  "Himachal Pradesh": [
    "Arki","Baddi","Baijnath","Banjar","Bilaspur","Chamba","Chopal","Dalhousie","Dehra","Dharamsala","Fatehpur",
    "Gagret","Hamirpur","Jogindernagar","Jubbal","Kangra","Kasauli","Keylong","Kinnaur","Kufri","Kullu",
    "Kurseong","Lahaul","Manali","Mandi","Nahan","Narkanda","Nurpur","Palampur","Paonta Sahib","Parwanoo",
    "Rampur","Recong Peo","Rohru","Sarkaghat","Shimla","Sirmaur","Solan","Spiti","Sundernagar","Theog",
    "Una","Yol",
  ],
  "Jharkhand": [
    "Adityapur","Baharagora","Balumath","Barkagaon","Barwadih","Bokaro","Bundu","Chaibasaa","Chakradharpur",
    "Chakulia","Chandankiyari","Chatra","Daltonganj","Deoghar","Dhanbad","Dumka","Garhwa","Ghatsila","Giridih",
    "Godda","Gumla","Hazaribagh","Hussainabad","Ichhagarh","Jamshedpur","Jharia","Jugsalai","Khunti","Koderma",
    "Latehar","Lohardaga","Madhupur","Musabani","Noamundi","Pakur","Palamu","Phusro","Rajmahal","Ramgarh",
    "Ranchi","Sahibganj","Saraikela","Simdega","Tenughat",
  ],
  "Karnataka": [
    "Aland","Alur","Ankola","Arsikere","Athani","Bagalkot","Ballari","Bangalore","Bengaluru","Belagavi","Bellary",
    "Bhadravati","Bhatkal","Bidar","Bijapur","Channapatna","Chamarajanagar","Chikkaballapur","Chikkamagaluru",
    "Chintamani","Chitradurga","Dandeli","Davanagere","Dharwad","Doddaballapur","Gadag","Gangavati","Gauribidanur",
    "Gokak","Gubbi","Gulbarga","Hassan","Haveri","Hiriyur","Holenarasipura","Hosakote","Hospet","Hubli",
    "Ilkal","Jamkhandi","Kadur","Kalaburagi","Karwar","Khanapur","Kolar","Kollegal","Koppal","Kushalnagar",
    "Lakshmeshwar","Madikeri","Magadi","Malkhed","Mandya","Mangaluru","Manipal","Mudhol","Mulbagal","Mundargi",
    "Mysore","Mysuru","Nagamangala","Nanjangud","Nargund","Pavagada","Puttur","Rabkavi Banhatti","Raichur",
    "Ramanagara","Ron","Sagara","Sandur","Sira","Sirsi","Sringeri","Sulya","Tiptur","Tumkur","Udupi","Vijayapura",
    "Yellapur","Yadgir",
  ],
  "Kerala": [
    "Adimali","Adoor","Alappuzha","Alathur","Angamaly","Attingal","Aluva","Badagara","Chalakudy","Changanacherry",
    "Chavakkad","Chengannur","Chittur","Ernakulam","Ettumanoor","Feroke","Guruvayur","Idukki","Irinjalakuda",
    "Kalpetta","Kanhangad","Kannur","Kasaragod","Kayamkulam","Kochi","Kodungallur","Kollam","Koothattukulam",
    "Kothamangalam","Kottarakkara","Kottayam","Kozhikode","Kunnamkulam","Malappuram","Manarcadu","Manjeri",
    "Mattancherry","Muvattupuzha","Nedumangad","Neyyattinkara","North Paravur","Ottapalam","Palakkad",
    "Payyannur","Perinthalmanna","Perumbavoor","Ponnani","Punalur","Ranni","Shornur","Taliparamba","Thalassery",
    "Thiruvananthapuram","Thrippunithura","Thrissur","Tirur","Vadakara","Varkala","Vaikom",
  ],
  "Madhya Pradesh": [
    "Alirajpur","Anuppur","Ashoknagar","Balaghat","Barwani","Betul","Bhind","Bhopal","Burhanpur","Chhatarpur",
    "Chhindwara","Damoh","Datia","Dewas","Dhar","Dindori","Gadarwara","Guna","Gwalior","Harda","Hoshangabad",
    "Indore","Itarsi","Jabalpur","Jhabua","Katni","Khandwa","Khargone","Lahar","Lashkar","Maihar","Mandla",
    "Mandsaur","Morena","Multai","Murwara","Narsimhapur","Narsinghpur","Neemuch","Nowgong","Pachmarhi","Panna",
    "Pipariya","Raisen","Rajgarh","Ratlam","Rewa","Sagar","Satna","Sehore","Seoni","Shahdol","Shajapur",
    "Sheopur","Shivpuri","Sidhi","Singrauli","Tikamgarh","Ujjain","Umaria","Vidisha",
  ],
  "Maharashtra": [
    "Achalpur","Ahmednagar","Akola","Akot","Alibag","Ambarnath","Ambejogai","Amravati","Amreli","Arvi",
    "Aurangabad","Badlapur","Baramati","Barshi","Beed","Bhandara","Bhiwandi","Bhiwani","Bhosari","Bhusawal",
    "Buldhana","Chalisgaon","Chandrapur","Chinchwad","Dapoli","Dhule","Dombivli","Gondia","Hadapsar","Hingoli",
    "Ichalkaranji","Jalgaon","Jalna","Karad","Kalyan","Khopoli","Kolhapur","Kolkata","Kopargaon","Kudal",
    "Latur","Loni","Lonavala","Mahabaleshwar","Malegaon","Malkapur","Mangalvedhe","Manmad","Mapusa","Miraj",
    "Mumbai","Nagpur","Nanded","Nashik","Navi Mumbai","Navi Peth","Newasa","Osmanabad","Pachora","Palghar",
    "Pandharpur","Panvel","Parbhani","Pen","Pimpri","Pune","Pusad","Raigad","Ratnagiri","Sangamner","Sangli",
    "Satara","Shrirampur","Sindhudurg","Solapur","Thane","Tumsar","Udgir","Ulhasnagar","Vasai","Vikhroli",
    "Wardha","Washi","Washim","Wai","Yavatmal",
  ],
  "Manipur": [
    "Bishnupur","Chandel","Churachandpur","Imphal","Jiribam","Kakching","Kamjong","Kangpokpi","Moirang",
    "Moreh","Noney","Pherzawl","Senapati","Tamenglong","Tengnoupal","Thoubal","Ukhrul",
  ],
  "Meghalaya": [
    "Baghmara","Cherrapunjee","Dawki","Jowai","Khliehriat","Mairang","Mawkyrwat","Mawlai","Mawphlang","Mawsynram",
    "Nongpoh","Nongstoin","Resubelpara","Shillong","Tura","Williamnagar",
  ],
  "Mizoram": [
    "Aizawl","Champhai","Hnahthial","Kolasib","Lawngtlai","Lunglei","Mamit","Saiha","Saitual","Serchhip",
    "Thenzawl","Tlabung","Zawlnuam",
  ],
  "Nagaland": [
    "Dimapur","Jalukie","Kohima","Longleng","Mokokchung","Mon","Peren","Phek","Tuensang","Wokha","Zunheboto",
  ],
  "Odisha": [
    "Angul","Asika","Balangir","Balasore","Baleswar","Baripada","Bargarh","Bhadrakh","Bhubaneswar","Bonai",
    "Boudh","Brahmapur","Bhanjanagar","Burla","Chhatrapur","Cuttack","Deogarh","Dhenkanal","Gunupur","Jagatsinghpur",
    "Jajpur","Jeypore","Jharsuguda","Joda","Kalahandi","Kandhamal","Karanjia","Kendrapara","Kendujhar","Keonjhar",
    "Khordha","Koraput","Kuchinda","Malkangiri","Mayurbhanj","Nabarangpur","Nayagarh","Nuapada","Paradip",
    "Puri","Rayagada","Rourkela","Sambalpur","Sonepur","Sundargarh","Talcher","Titlagarh",
  ],
  "Punjab": [
    "Abohar","Adampur","Ajnala","Amritsar","Anandpur Sahib","Barnala","Batala","Bathinda","Dhuri","Dera Bassi",
    "Doraha","Faridkot","Fatehgarh Sahib","Fazilka","Ferozepur","Firozpur","Gobindgarh","Gurdaspur","Guruharsahai",
    "Hoshiarpur","Jagraon","Jalandhar","Khanna","Kot Kapura","Kurali","Longowal","Ludhiana","Machhiwara","Malerkotla",
    "Mansa","Moga","Mohali","Morinda","Muktsar","Nabha","Nangal","Nawanshahr","Nakodar","Pathankot","Patiala",
    "Phillaur","Phagwara","Qadian","Rajpura","Rampura Phul","Ropar","Rupnagar","Sangrur","Shaheed Bhagat Singh Nagar",
    "Sirhind","Sunam","Tarn Taran","Zira",
  ],
  "Rajasthan": [
    "Abu Road","Ajmer","Alwar","Amet","Anupgarh","Atru","Balotra","Banswara","Baran","Barmer","Beawar","Bharatpur",
    "Bhilwara","Bikaner","Bundi","Chittorgarh","Churu","Dausa","Dholpur","Didwana","Dungapur","Fatehpur",
    "Gangapur City","Hanumangarh","Jaipur","Jaisalmer","Jalore","Jhalawar","Jhunjhunu","Jodhpur","Karauli",
    "Kishangarh","Kota","Kotputli","Kumbalgarh","Laxmangarh","Makrana","Merta","Mount Abu","Nagaur","Nasirabad",
    "Nathdwara","Neem ka Thana","Nohar","Pali","Phalodi","Pushkar","Rajsamand","Ramganj Mandi","Ratangarh",
    "Sadri","Sagwara","Salumbar","Sambhar","Sawai Madhopur","Shahpura","Sikar","Sirohi","Sri Ganganagar",
    "Sujangarh","Suratgarh","Takhatgarh","Tikamgarh","Tonk","Udaipur",
  ],
  "Sikkim": [
    "Gangtok","Geyzing","Gyalshing","Jorethang","Mangan","Namchi","Nayabazar","Pakyong","Rangpo","Ravangla",
    "Singtam","Soreng","Yuksom",
  ],
  "Tamil Nadu": [
    "Arakkonam","Ariyalur","Aruppukkottai","Attur","Bhavani","Chennai","Chengalpet","Chidambaram","Coimbatore",
    "Cuddalore","Coonoor","Dharmapuri","Dindigul","Erode","Gudiyatham","Hosur","Kanchipuram","Karaikudi",
    "Karur","Krishnagiri","Kumbakonam","Kurichi","Lalgudi","Madurai","Mannargudi","Mettur","Mayiladuthurai",
    "Nagercoil","Namakkal","Natham","Nilgiris","Oddanchatram","Ooty","Palani","Paramakudi","Pattukottai",
    "Perambalur","Pollachi","Pudukkottai","Rajapalayam","Ranipet","Rasipuram","Salem","Sankarankoil","Sivaganga",
    "Sivakasi","Tambaram","Tenkasi","Thanjavur","The Nilgiris","Thiruvarur","Thoothukudi","Tiruchendur",
    "Tiruchirappalli","Tirunelveli","Tirupattur","Tiruppur","Tiruvannamalai","Tiruvarur","Tuticorin","Udhagamandalam",
    "Vaniyambadi","Vellore","Viluppuram","Virudhunagar",
  ],
  "Telangana": [
    "Adilabad","Bhadradri Kothagudem","Bhongir","Bodhan","Gadwal","Hyderabad","Jagitial","Jagtial","Jangaon",
    "Jayashankar Bhupalpally","Jogulamba Gadwal","Kamareddy","Karimnagar","Khammam","Kodangal","Korutla","Kothagudem",
    "Kyathampally","Mahabubnagar","Mahabubabad","Mancherial","Medak","Medchal–Malkajgiri","Miryalaguda",
    "Nalgonda","Narayanpet","Nirmal","Nizamabad","Palwancha","Peddapalli","Ramagundam","Ranga Reddy","Secunderabad",
    "Siddipet","Suryapet","Tandur","Vikarabad","Wanaparthy","Warangal","Yadadri Bhuvanagiri","Zahirabad",
  ],
  "Tripura": [
    "Agartala","Ambassa","Belonia","Bishalgarh","Dharmanagar","Kailasahar","Khowai","Kumarghat","Melaghar",
    "Sabroom","Sonamura","Teliamura","Udaipur",
  ],
  "Uttar Pradesh": [
    "Agra","Aligarh","Allahabad","Ambedkar Nagar","Amethi","Amroha","Auraiya","Ayodhya","Azamgarh","Baghpat",
    "Bahraich","Ballia","Balrampur","Banda","Barabanki","Bareilly","Basti","Bijnor","Budaun","Bulandshahr",
    "Chandauli","Chitrakoot","Deoria","Etah","Etawah","Farrukhabad","Fatehpur","Firozabad","Ghaziabad",
    "Ghazipur","Gonda","Gorakhpur","Hamirpur","Hardoi","Hapur","Hathras","Jalaun","Jhansi","Jyotiba Phule Nagar",
    "Kannauj","Kanpur","Kaushambi","Kheri","Kushinagar","Lakhimpur","Lalitpur","Lucknow","Maharajganj","Mahoba",
    "Mainpuri","Mathura","Mau","Meerut","Mirzapur","Moradabad","Muzaffarnagar","Noida","Pilibhit","Pratapgarh",
    "Prayagraj","Raebareli","Rampur","Saharanpur","Sambhal","Shahjahanpur","Shamli","Shravasti","Siddharthnagar",
    "Sitapur","Sonbhadra","Sultanpur","Unnao","Varanasi",
  ],
  "Uttarakhand": [
    "Almora","Augustmuni","Bageshwar","Barkot","Bazpur","Berinag","Bhimtal","Bhowali","Chakrata","Chamba",
    "Champawat","Chinyalisaur","Dehradun","Deoprayag","Devprayag","Dhanaulti","Dharchula","Doiwala","Dugadda",
    "Dwarahat","Gauchar","Gopeshwar","Haridwar","Haldwani","Jaspur","Joshimath","Kaladhungi","Kanda","Kapkot",
    "Karnaprayag","Kashipur","Khatima","Kotdwar","Lansdowne","Lohaghat","Meerut","Munsyari","Mussoorie",
    "Nainital","New Tehri","Pauri","Pithoragarh","Pokhari","Purola","Raipur","Ramnagar","Ranikhet","Rishikesh",
    "Roorkee","Rudraprayag","Rudrapur","Satpuli","Shyampur","Sitarganj","Srinagar Garhwal","Tehri","Tharali",
    "Udham Singh Nagar","Ukhimath","Uttarkashi","Vikasnagar",
  ],
  "West Bengal": [
    "Alipurduar","Arambagh","Asansol","Balurghat","Bankura","Barasat","Barrackpore","Berhampore","Birbhum",
    "Bishnupur","Bongaon","Budge Budge","Burdwan","Chakdaha","Chandannagar","Chinsurah","Cooch Behar","Contai",
    "Darjeeling","Diamond Harbour","Durgapur","English Bazar","Gangarampur","Ghatal","Habra","Haldia","Hugli",
    "Jalpaiguri","Jhargram","Kalna","Kalyani","Kharagpur","Koch Bihar","Kolkata","Krishnanagar","Ksetramohan",
    "Kurseong","Malda","Medinipur","Midnapore","Murshidabad","Nabadwip","Nadia","North 24 Parganas","Purulia",
    "Raiganj","Ranaghat","Serampore","Siliguri","South 24 Parganas","Suri","Tamluk","Uluberia",
  ],
  "Andaman & Nicobar Islands": [
    "Campbell Bay","Car Nicobar","Diglipur","Ferrargunj","Havelock Island","Kamorta","Long Island","Mayabunder",
    "Neil Island","Port Blair","Rangat","Wandoor",
  ],
  "Chandigarh": ["Chandigarh","Manimajra","Panchkula"],
  "Dadra & Nagar Haveli and Daman & Diu": ["Amli","Dadra","Daman","Diu","Khanvel","Naroli","Silvassa"],
  "Delhi": [
    "Alipur","Bawana","Burari","Civil Lines","Connaught Place","Dabri","Deoli","Dwarka","Fatehpur Beri",
    "Ghitorni","Hastsal","Janakpuri","Karawal Nagar","Keshavpuram","Kirari Suleman Nagar","Loni Road","Mangolpuri",
    "Mustafabad","Mundka","Narela","Nand Nagri","Nangloi","New Delhi","Nilothi","Palam","Pitampura","Rohini",
    "Saraswati Vihar","Seelampur","Shahdara","Uttam Nagar",
  ],
  "Jammu & Kashmir": [
    "Anantnag","Awantipora","Bandipora","Baramulla","Batote","Bijbehara","Budgam","Chenani","Doda","Ganderbal",
    "Handwara","Jammu","Kathua","Katra","Kishtwar","Kulgam","Kupwara","Mendhar","Pampore","Pulwama","Qazigund",
    "Rajouri","Ramban","Reasi","Shopian","Sopore","Srinagar","Samba","Sunderbani","Tral","Udhampur",
  ],
  "Ladakh": [
    "Chushul","Diskit","Drass","Hanle","Kargil","Khalatse","Leh","Nubra","Nyoma","Padum","Sankoo","Shey","Zanskar",
  ],
  "Lakshadweep": [
    "Agatti","Amini","Andrott","Androth","Chetlat","Kavaratti","Kiltan","Minicoy",
  ],
  "Puducherry": [
    "Ariyankuppam","Karaikal","Kurumbapet","Mahe","Murungapakkam","Oulgaret","Puducherry","Villianur","Yanam",
  ],
};
